name: secret scan

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
